name: MinecraftGambling
version: 1.5
author: OnlineMetLesley
main: me.OnlineMetLesley.com.MinecraftGambling.Main
depend: [Vault, TitleAPI]


commands:
  gamble:
    description: Main command off Minecraft Gambling
    
